### ISSUE TITLE
vcf2parquet creates broken parquet files

### ISSUE THREAD

**Issue by Hoeze** [natir/vcf2parquet#2]
Hi, your tool seems to create broken parquet files:

```bash
vcf2parquet -i test.vcf.gz convert -o test.parquet
pqrs cat test.parquet
```

Results in:
```
##################
File: test.parquet
##################

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: General("insufficient values read from column - expected: 1024, got: 0")', [...]/.cargo/registry/src/github.com-1ecc6299db9ec823/parquet-12.0.0/src/record/reader.rs:578:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I tried this with both, your bioconda version and a self-built from your latest version on github.

[test.vcf.gz](https://github.com/natir/vcf2parquet/files/10569620/test.vcf.gz)

**Comment by Hoeze** [comment]
full backtrace:

<details>

```rust
stack backtrace:
   0:     0x55e338358afd - std::backtrace_rs::backtrace::libunwind::trace::hee598835bc88d35b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55e338358afd - std::backtrace_rs::backtrace::trace_unsynchronized::h9cdc730ba5cf5d72
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55e338358afd - std::sys_common::backtrace::_print_fmt::h75aeaf7ed30e43fa
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55e338358afd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h606862f787600875
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55e33837dd9c - core::fmt::write::he803f0f418caf762
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:     0x55e338354f48 - std::io::Write::write_fmt::h70bc45872f37e7bb
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:     0x55e33835ab97 - std::sys_common::backtrace::_print::h64d038cf8ac3e13e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55e33835ab97 - std::sys_common::backtrace::print::h359300b4a7fccf65
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55e33835ab97 - std::panicking::default_hook::{{closure}}::hf51be35e2f510149
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:     0x55e33835a860 - std::panicking::default_hook::h03ca0f22e1d2d25e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:     0x55e33835b2e9 - std::panicking::rust_panic_with_hook::h3b7380e99b825b63
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:698:17
  11:     0x55e33835afd7 - std::panicking::begin_panic_handler::{{closure}}::h8e849d0710154ce0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
  12:     0x55e338358fc4 - std::sys_common::backtrace::__rust_end_short_backtrace::hedcdaddbd4c46cc5
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55e33835ace9 - rust_begin_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
  14:     0x55e337d29bd3 - core::panicking::panic_fmt::he1bbc7336d49a357
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
  15:     0x55e337d29cc3 - core::result::unwrap_failed::h719f957ed74f93fd
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
  16:     0x55e337e691fc - parquet::record::reader::Reader::advance_columns::h95948c55cde4527e
  17:     0x55e337e69269 - parquet::record::reader::Reader::advance_columns::h95948c55cde4527e
  18:     0x55e337e699c2 - <parquet::record::reader::RowIter as core::iter::traits::iterator::Iterator>::next::ha2e6e7d4c93cf2ed
  19:     0x55e337d851d6 - pqrs::utils::print_rows::hf887e24c0dac8028
  20:     0x55e337d55429 - pqrs::commands::cat::execute::hfef9a501f5b4760a
  21:     0x55e337d4e995 - pqrs::main::h157e2c31c1b57ff2
  22:     0x55e337d7f0e6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h23a941f7e868e04c
  23:     0x55e337d88b48 - std::rt::lang_start::{{closure}}::h2f512e498f12ac49
  24:     0x55e3383581e1 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb7014f43484a8b4e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:259:13
  25:     0x55e3383581e1 - std::panicking::try::do_call::h7bc9dc436daeb8c7
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  26:     0x55e3383581e1 - std::panicking::try::h653d68a27ff5f175
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  27:     0x55e3383581e1 - std::panic::catch_unwind::h9d739f9f59895e68
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  28:     0x55e3383581e1 - std::rt::lang_start_internal::{{closure}}::hf006f2bc7ce22bbe
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:48
  29:     0x55e3383581e1 - std::panicking::try::do_call::hfb39d6df61a2e69f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  30:     0x55e3383581e1 - std::panicking::try::h13e2d225134958ac
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  31:     0x55e3383581e1 - std::panic::catch_unwind::h3bd49b5a5dfb1a50
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  32:     0x55e3383581e1 - std::rt::lang_start_internal::h2ba92edce36c035e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:20
  33:     0x55e337d4f0f2 - main
  34:     0x7f550c4fdd85 - __libc_start_main
  35:     0x55e337d2a45e - _start
  36:                0x0 - <unknown>
```

</details>

**Comment by natir** [comment]
Thanks for this issue.

Ok my last commit seems fix your trouble can you check it ? If not please reopen this issue.

After some cleaning I will perform a new bioconda release.

**Comment by Hoeze** [comment]
Thanks for your quick answer @natir.
I tried your last commit but with the same result:
```
# cargo install --list
vcf2parquet v0.3.0 (https://github.com/natir/vcf2parquet.git#73cf420e):
    vcf2parquet
```

My guess is that it fails to write the INFO_SV columns as these have to be nullable, but your file schema has them as "REQUIRED":
```yaml
# pqrs schema test.parquet                                                                                                                                                       
Metadata for file: test.parquet

version: 2
num of rows: 49920
created by: Arrow2 - Native Rust implementation of Arrow
metadata:
  ARROW:schema: /////2cDAAAEAAAA8v///xQAAAAEAAEAAAAKAAsACAAKAAQA+P///wwAAAAIAAgAAAAEAAkAAAD4AgAAqAIAACgCAADkAQAAXAEAABgBAACYAAAASAAAAAQAAADs////LAAAACAAAAAYAAAABQAAABAAEQAEAAAAEAAIAAAADAAAAAAA/P///wQABAALAAAAaW5mb19TVlRZUEUA7P///zgAAAAgAAAAGAAAAAIAAAAQABEABAAAABAACAAAAAwAAAAAAPT///8gAAAAAQAAAAgACQAEAAgACAAAAGluZm9fRU5EAAAAAOz///9sAAAAYAAAABgAAAAMAAAAEAARAAQAAAAQAAgAAAAMAAEAAAAEAAAA7P///ywAAAAgAAAAGAAAAAUAAAAQABEABAAAABAACAAAAAwAAAAAAPz///8EAAQABgAAAGZpbHRlcgAA/P///wQABAAGAAAAZmlsdGVyAADs////MAAAACAAAAAYAAAAAQMAABAAEgAEABAAEQAIAAAADAAAAAAA+v///wEABgAGAAQABwAAAHF1YWxpdHkA7P///3AAAABkAAAAGAAAAAwAAAAQABEABAAAABAACAAAAAwAAQAAAAQAAADs////LAAAACAAAAAYAAAABQAAABAAEQAEAAAAEAAIAAAADAAAAAAA/P///wQABAAJAAAAYWx0ZXJuYXRlAAAA/P///wQABAAJAAAAYWx0ZXJuYXRlAAAA7P///ywAAAAgAAAAGAAAAAUAAAAQABEABAAAABAACAAAAAwAAAAAAPz///8EAAQACQAAAHJlZmVyZW5jZQAAAOz///9oAAAAXAAAABgAAAAMAAAAEAARAAQAAAAQAAgAAAAMAAEAAAAEAAAA7P///ywAAAAgAAAAGAAAAAUAAAAQABEABAAAABAACAAAAAwAAAAAAPz///8EAAQAAgAAAGlkAAD8////BAAEAAoAAABpZGVudGlmaWVyAADs////OAAAACAAAAAYAAAAAgAAABAAEQAEAAAAEAAIAAAADAAAAAAA9P///yAAAAABAAAACAAJAAQACAAIAAAAcG9zaXRpb24AAAAA7P///ywAAAAgAAAAGAAAAAUAAAAQABEABAAAABAACAAAAAwAAAAAAPz///8EAAQACgAAAGNocm9tb3NvbWUA
message root {
  REQUIRED BYTE_ARRAY chromosome (STRING);
  REQUIRED INT32 position;
  REQUIRED group identifier (LIST) {
    REPEATED group list {
      REQUIRED BYTE_ARRAY id (STRING);
    }
  }
  REQUIRED BYTE_ARRAY reference (STRING);
  REQUIRED group alternate (LIST) {
    REPEATED group list {
      REQUIRED BYTE_ARRAY alternate (STRING);
    }
  }
  OPTIONAL FLOAT quality;
  REQUIRED group filter (LIST) {
    REPEATED group list {
      REQUIRED BYTE_ARRAY filter (STRING);
    }
  }
  REQUIRED INT32 info_END;
  REQUIRED BYTE_ARRAY info_SVTYPE (STRING);
}
```

**Comment by Hoeze** [comment]
OK, so the problem is still the same:
```bash
# cargo install --list
vcf2parquet v0.3.0 (https://github.com/natir/vcf2parquet.git#1f708d9f):
    vcf2parquet

# vcf2parquet -i test.vcf convert -o test.parquet   
# pqrs schema test.parquet
Metadata for file: test.parquet

version: 2
num of rows: 49067
created by: Arrow2 - Native Rust implementation of Arrow
metadata:
  ARROW:schema: /////2cDAAAEAAAA8v///xQAAAAEAAEAAAAKAAsACAAKAAQA+P///wwAAAAIAAgAAAAEAAkAAAD4AgAAqAIAACgCAADkAQAAXAEAABgBAACYAAAASAAAAAQAAADs////LAAAACAAAAAYAAAABQAAABAAEQAEAAAAEAAIAAAADAAAAAAA/P///wQABAALAAAAaW5mb19TVlRZUEUA7P///zgAAAAgAAAAGAAAAAIAAAAQABEABAAAABAACAAAAAwAAAAAAPT///8gAAAAAQAAAAgACQAEAAgACAAAAGluZm9fRU5EAAAAAOz///9sAAAAYAAAABgAAAAMAAAAEAARAAQAAAAQAAgAAAAMAAEAAAAEAAAA7P///ywAAAAgAAAAGAAAAAUAAAAQABEABAAAABAACAAAAAwAAAAAAPz///8EAAQABgAAAGZpbHRlcgAA/P///wQABAAGAAAAZmlsdGVyAADs////MAAAACAAAAAYAAAAAQMAABAAEgAEABAAEQAIAAAADAAAAAAA+v///wEABgAGAAQABwAAAHF1YWxpdHkA7P///3AAAABkAAAAGAAAAAwAAAAQABEABAAAABAACAAAAAwAAQAAAAQAAADs////LAAAACAAAAAYAAAABQAAABAAEQAEAAAAEAAIAAAADAAAAAAA/P///wQABAAJAAAAYWx0ZXJuYXRlAAAA/P///wQABAAJAAAAYWx0ZXJuYXRlAAAA7P///ywAAAAgAAAAGAAAAAUAAAAQABEABAAAABAACAAAAAwAAAAAAPz///8EAAQACQAAAHJlZmVyZW5jZQAAAOz///9oAAAAXAAAABgAAAAMAAAAEAARAAQAAAAQAAgAAAAMAAEAAAAEAAAA7P///ywAAAAgAAAAGAAAAAUAAAAQABEABAAAABAACAAAAAwAAAAAAPz///8EAAQAAgAAAGlkAAD8////BAAEAAoAAABpZGVudGlmaWVyAADs////OAAAACAAAAAYAAAAAgAAABAAEQAEAAAAEAAIAAAADAAAAAAA9P///yAAAAABAAAACAAJAAQACAAIAAAAcG9zaXRpb24AAAAA7P///ywAAAAgAAAAGAAAAAUAAAAQABEABAAAABAACAAAAAwAAAAAAPz///8EAAQACgAAAGNocm9tb3NvbWUA
message root {
  REQUIRED BYTE_ARRAY chromosome (STRING);
  REQUIRED INT32 position;
  REQUIRED group identifier (LIST) {
    REPEATED group list {
      REQUIRED BYTE_ARRAY id (STRING);
    }
  }
  REQUIRED BYTE_ARRAY reference (STRING);
  REQUIRED group alternate (LIST) {
    REPEATED group list {
      REQUIRED BYTE_ARRAY alternate (STRING);
    }
  }
  OPTIONAL FLOAT quality;
  REQUIRED group filter (LIST) {
    REPEATED group list {
      REQUIRED BYTE_ARRAY filter (STRING);
    }
  }
  REQUIRED INT32 info_END;
  REQUIRED BYTE_ARRAY info_SVTYPE (STRING);
}
# pqrs cat test.parquet

##################
File: test.parquet
##################

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: General("insufficient values read from column - expected: 1024, got: 0")',[...]/.cargo/registry/src/github.com-1ecc6299db9ec823/parquet-12.0.0/src/record/reader.rs:578:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by natir** [comment]
Sorry it seems I have a little problem in my git management the last version is 0.3.1. With the v0.3.1 tag it should work, if I base it on the test file you sent me.

**Comment by Hoeze** [comment]
Thanks a lot @natir :raised_hands: 

 I tried v0.3.1. It still fails with `pqrs`:
```bash
# vcf2parquet -i test.vcf convert -o test.parquet
# pqrs cat test.parquet

##################
File: test.parquet
##################

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: General("insufficient values read from column - expected: 1024, got: 0")', /home/hoelzlwimmerf/.cargo/registry/src/github.com-1ecc6299db9ec823/parquet-12.0.0/src/record/reader.rs:578:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

# vcf2parquet --version
vcf2parquet 0.3.1
```
However, I also tried with PyArrow and this works correctly, so I guess this is now a problem with `pqrs`:
```python
import pyarrow as pa
import pyarrow.parquet as pq

pq.read_table("test.parquet")

Out[3]: 
pyarrow.Table
chromosome: string not null
position: int32 not null
identifier: list<id: string not null> not null
  child 0, id: string not null
reference: string not null
alternate: list<alternate: string not null> not null
  child 0, alternate: string not null
quality: float
filter: list<filter: string not null> not null
  child 0, filter: string not null
info_END: int32 not null
info_SVTYPE: string not null
----
chromosome: [["chr1","chr1","chr1","chr1","chr1","chr1","chr1","chr1","chr1","chr1",...,"chr1","chr1","chr1","chr1","chr1","chr1","chr1","chr1","chr1","chr1"]]
position: [[10427,10427,10439,10440,13459,14397,15219,16766,16871,29231,...,6094404,6094410,6094858,6095109,6095224,6095265,6095278,6095299,6095300,6095491]]
identifier: [[["chr1:10426:10429:ACC>A"],["chr1:10426:10429:ACC>*"],["chr1:10438:10440:AC>*"],["chr1:10439:10440:C>*"],["chr1:13458:13462:CAGA>C"],["chr1:14396:14399:CTG>C"],["chr1:15218:15230:GAGCCACCTCCC>G"],["chr1:16765:16766:C>CT"],["chr1:16870:16872:GC>G"],["chr1:29230:29231:G>T"],...,["chr1:6094403:6094404:C>A"],["chr1:6094409:6094410:C>T"],["chr1:6094857:6094858:C>T"],["chr1:6095108:6095109:G>A"],["chr1:6095223:6095224:C>T"],["chr1:6095264:6095265:G>A"],["chr1:6095277:6095278:C>T"],["chr1:6095298:6095299:C>T"],["chr1:6095299:6095300:G>A"],["chr1:6095490:6095491:C>G"]]]
reference: [["ACC","ACC","AC","C","CAGA","CTG","GAGCCACCTCCC","C","GC","G",...,"C","C","C","G","C","G","C","C","G","C"]]
alternate: [[["A"],["*"],["*"],["*"],["C"],["C"],["G"],["CT"],["G"],["T"],...,["A"],["T"],["T"],["A"],["T"],["A"],["T"],["T"],["A"],["G"]]]
quality: [[null,null,null,null,null,null,null,null,null,null,...,null,null,null,null,null,null,null,null,null,null]]
filter: [[[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],...,[""],[""],[""],[""],[""],[""],[""],[""],[""],[""]]]
info_END: [[10429,10429,10440,10440,13462,14399,15230,16766,16872,29231,...,6094404,6094410,6094858,6095109,6095224,6095265,6095278,6095299,6095300,6095491]]
info_SVTYPE: [["","","","","","","","","","",...,"","","","","","","","","",""]]
```

The only difference is that there are still empty strings instead of `null` values in `info_SVTYPE`.
Would it maybe be possible to have `OPTIONAL` Info fields if the VCF record does not contain the field? :smile:

**Comment by natir** [comment]
On my understanding of vcf specification if an INFO field have a Number value set to 1 is mandatory not optional. In your vcf example header we can found:
```
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="">
```

So for me info_SVTYPE couldn't be null but by rereading the specification of version 4.3 of vcf it seems impossible to me to have an optional info field. What did I miss?

**Comment by Hoeze** [comment]
The INFO fields are all written in the form of `[$key=$value]*`. In my case, the field `SVTYPE` is missing in some rows.
I am not exactly sure what the VCF file spec says for that, but I have seen this a lot when you mix e.g. normal variants with structural variants.
This is why I would just denote this in the parquet file as `missing`.

For example, the [Glow framework](https://github.com/projectglow/glow/) also simply assumes that all INFO fields are optional.

**Comment by natir** [comment]
After what discussion around the question is an info field optional or not? An intensive consultation of the specifications. The question doesn't seem to be clear-cut, I think the best solution is to create an option that makes info fields optional.

**Comment by Hoeze** [comment]
Yes, this would be a great solution! :+1:
